### ISSUE TITLE
[BUG] Error trying to add image to screen

### ISSUE THREAD

**Issue by komjum6** [ObaraEmmanuel/Formation#34]
**Describe the bug**

An error when trying to add image to the screen:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\hoverset\ui\widgets.py", line 1040, in _click
    self._on_click(event)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\hoverset\ui\widgets.py", line 1035, in <lambda>
    self._on_click = lambda event: callback(event, *args, **kwargs)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\studio\feature\components.py", line 102, in select
    self.deselect()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\studio\feature\components.py", line 111, in deselect
    self.controller.deselect(self, silently)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\studio\feature\components.py", line 186, in deselect
    self._on_selection_change(self.selected)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\studio\feature\components.py", line 168, in <lambda>
    self._on_selection_change = lambda component: func(component, *args, **kwargs)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\studio\tools\canvas.py", line 1131, in set_draw
    self._set_cursor()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\studio\tools\canvas.py", line 1141, in _set_cursor
    self._reset_cursor()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python310\lib\site-packages\studio\tools\canvas.py", line 1135, in _reset_cursor
    self.canvas.configure(cursor=self._cursor)
AttributeError: 'NoneType' object has no attribute 'configure'

**To Reproduce**

1. Go to search
2. Type image
3. Try to drag image

**Expected behavior**

Image added to screen

**Screenshots**

![image](https://github.com/ObaraEmmanuel/Formation/assets/6501519/eb92ff9c-0b4e-41fd-b7c0-b88a95774944)

**Your environment**
 - OS: Windows
 - `formation` Version latest
 - Python version: 3.10
 - tk version: latest

**Additional context**
There was a commit 3 days ago which changed the code associated with this

**Comment by ObaraEmmanuel** [comment]
Thanks for reporting this. I start looking into it.

**Comment by ObaraEmmanuel** [comment]
The problem is that you were trying to add a canvas image to something other than a canvas. This should never be possible but the search mechanism was poorly implemented allowing this illegal scenario. I have since fixed that. To add an image to the screen, first place a `Label` widget on the design and set its `image` property to your desired image. To add an image to a `Canvas` first ensure that it is selected then the `Image` item will appear in the search on the component pane.
 > Note that Canvas components should not be dragged onto the design but instead selected and drawn onto the canvas.

**Comment by komjum6** [comment]
Thank you, it works now I know that. Would also have been nice if there was a way to make the image scale with the scale of the label, but I'll make changes to the image myself then. Thanks again 👍
